name: Run Tests

on:
  push:
    branches:
      - main  

jobs:
  training:
    name: Training
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Use the version you're working with

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model/requirements.txt 

      # Run tests
      - name: Run tests with pytest
        run: |
          pytest model/test-trainmodel.py
